name: Spark Data Processing

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  process-data:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Spark
        uses: vemonet/setup-spark@v1
        with:
          spark-version: "3.5.3"

      - name: Run Spark Data Processing
        run: |
          spark-submit people.py

      - name: Upload Processed Data
        uses: actions/upload-artifact@v3
        with:
          name: processed-data
          path: results/data.json
