name: Spark Data Processing

on:
  push:
    branches:
      - main

jobs:
  spark-processing:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Java
        uses: actions/setup-java@v2
        with:
          java-version: '11'

      - name: Set up Spark
        uses: vemonet/setup-spark@v1
        with:
          spark-version: '3.5.3'

      - name: Install dependencies
        run: |
          sudo apt-get install -y python3-pip
          pip3 install -r requirements.txt

      - name: Run Spark Data Processing
        run: |
          $SPARK_HOME/bin/spark-submit --master local data_processing.py

      - name: Move processed data to output directory
        run: |
          mkdir -p output
          mv results/* output/

      - name: Verify processed data
        run: |
          ls -l output/
