name: Spark Data Processing

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  process-data:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Spark
        uses: vemonet/setup-spark@v1
        with:
          spark-version: "3.5.3"

      - name: Run Spark Data Processing
        run: |
          $SPARK_HOME/bin/spark-submit people.py

      - name: Upload processed data
        uses: actions/upload-artifact@v3
        with:
          name: processed-results
          path: results/
